name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
         token: ${{ secrets.ACCESS_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Update README
      run: python3 update_content_table.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name 'Aysr01'
        git config --global user.email 'sarab.ayoub@inemail.ine.inpt.ma'
        git add README.md
        git commit -m "Update README"
        git push
